package dev.said.enums;

public enum UserRole {
    ADMINISTRATOR,
    DEVELOPER_BACKEND,
    DEVELOPER_FRONTEND,
    DEVELOPER_FULLSTACK,
    DEVELOPER_MOBILE,
    DEVELOPER_GAME,
    DEVELOPER_TESTER,
    SECURITY,
    HR,
    MANAGER,
    CREATIVE_DIRECTOR,
    DESIGNER,
    MARKETING,
    FINANCE,
    ACCOUNTANT,
    ANALYST,
    CONTENT_MANAGER,
    COPYWRITER,
    DESIGNER_3D,
    WORKER


}
